### ISSUE TITLE
expressjs with ES6

### ISSUE THREAD

**Issue by mshahat** [expressjs/generator#147]
Hello, 

a bit new to this stack of javascript frameworks. I'm using Intellij with node and express plugin. 

I've generated a new project using express generator, however i keep on getting warnings against the use of var ... e.g. 
`var express = require('express');`

is there any guide around generating express.js project for use with ES6 ? or any articles about possible acceptable changes to fit with ES6 ? 

Thanks, 

p.s. i'm using node 6.9.2, espress 4.14, npm 3.10.8 and intellij ultimate 2016.3

**Comment by pravdomil** [comment]
https://github.com/expressjs/generator/pull/148

**Comment by dougwilson** [comment]
"var" is just as valid as "const". The only thing that would yell at you is if you are using a linter, which you can just ignite this file.

**Comment by dougwilson** [comment]
Remember, ES6 is basically just new syntax on top of ES5; valid ES5 is valid ES6, including the var keyword is 100% valid ES6. I assume you have some kind of linter on that is trying to encourage you to use const and let instead of var for some reason. If that is the case, you have outgrown this generator project, though there is a WIP PR to generate a newer style ES6 project, but that is not required by Node.js or anything, just for... looks?

**Comment by berkandirim** [comment]
You can use this Yeoman generator https://github.com/ofkindness/generator-express-es6
