### ISSUE TITLE
npm start fails

### ISSUE THREAD

**Issue by BalasseThibault** [expressjs/generator#149]
Hi guys,

I tried to run the generator and found some errors, i can't solve those problems.

This is what i have when i try to run the npm start.

![erreur 1](https://cloud.githubusercontent.com/assets/22323550/22183189/56bbb9c6-e0b8-11e6-96dc-634f510b7434.png)

![erreur 2](https://cloud.githubusercontent.com/assets/22323550/22183191/5e8575ca-e0b8-11e6-81a2-1ceaa10e07f6.png)

Impossible to visit my http://localhost:3000/ and don't know what to do...

This is my package.json : 

![erreur 3](https://cloud.githubusercontent.com/assets/22323550/22183211/b1ce3942-e0b8-11e6-939c-a5e1fcea627f.png)

My npm-debug.txt

![erreur 4](https://cloud.githubusercontent.com/assets/22323550/22183242/7d67154c-e0b9-11e6-83a2-ae908367ffe2.png)

Ask me if you want more screens to solve my problem.

Thanks !

**Comment by gokaygurcan** [comment]
Hello,

Are you really sure that the errors are related to the generator? Because in the first screenshot, it says "failed to connect to server localhost:27017" which is related to MongoDB. 

I'd suggest you to remove node_modules and re-install dependencies as a first step:
`rm -rf node_modules && npm install` 

Also, can you please add more information about your addition to the original code? What packages did you add and what was your changes?

**Comment by dougwilson** [comment]
Yea, I'm not sure if there is an issue with the generator itself, since it doesn't do anything that would connect to a database, which is what your error is about. I would suggest dropping by the support channel https://gitter.im/expressjs/express
