### ISSUE TITLE
scss support

### ISSUE THREAD

**Issue by thoughtbyte** [expressjs/generator#150]
It looks like the sass support works fine, but there's no option for scss by default, or am I missing something? I can submit a pull request tomorrow if I haven't missed anything :D

**Comment by thoughtbyte** [comment]
it looks like theres a compass flag, but that uses compass middleware. should there be a scss flag that uses node-sass with indent syntax set to fault?

**Comment by gokaygurcan** [comment]
```bash
$ express -h

  Usage: express [options] [dir]

  Options:

    -h, --help          output usage information
    -V, --version       output the version number
    -e, --ejs           add ejs engine support (defaults to jade)
        --hbs           add handlebars engine support
    -H, --hogan         add hogan.js engine support
    -c, --css <engine>  add stylesheet <engine> support (less|stylus|compass|sass) (defaults to plain css)
        --git           add .gitignore
    -f, --force         force on non-empty directory
```

When you create a project with `express -css sass` command, you can use both `sass` and `scss` file extensions and node-sass will handle them both. This command will add `node-sass-middleware` dependency and use it as 
```js
app.use(require('node-sass-middleware')({
  src: path.join(__dirname, 'public'),
  dest: path.join(__dirname, 'public'),
  indentedSyntax: true,
  sourceMap: true
}));
```
in your code. As you can see from [their README](https://github.com/sass/node-sass-middleware), it recompiles both sass and scss files: 
> Recompile .scss or .sass files automatically for connect and express based http servers.

I don't get where the problem is. Do you exactly want a css option like `scss` which will eventually do the same thing as `sass`? Or is there anything that you can do with another middleware but not this one?

**Comment by dougwilson** [comment]
I just took a look into this and indeed, `.scss` is not compiled with the `--css=sass` option, even though `node-sass-middleware` can do it. Looks like it's because the `indentedSyntax` option for the module chooses between `.scss` and `.sass` support.

Adding a `scss` option that outputs without that option will get `scss` support as a direct option :)

**Comment by dougwilson** [comment]
So looking more into this, the `--css` is meant to declare the engine you want to use, which is going to be `sass` for the sass engine. I'm updating the generator to include a comment for what code to change to choose between sass and scss files for the sass engine 👍

**Comment by dougwilson** [comment]
Generating with `--css=sass` will now have the following code block in `app.js`:
```js
app.use(sassMiddleware({
  src: path.join(__dirname, 'public'),
  dest: path.join(__dirname, 'public'),
  indentedSyntax: true, // true = .sass and false = .scss
  sourceMap: true
}));
```
