### ISSUE TITLE
Default view engine to pug, not jade.

### ISSUE THREAD

**Issue by fluxsauce** [expressjs/generator#166]
https://pugjs.org/api/migration-v2.html

> Due to a trademark issue, the project name has been changed from “Jade” to “Pug” in conjunction with the release of Pug 2.

The package should be updated and the templates should be renamed as well.

Sorry for the potential duplicate; after I submitted this, I noticed  https://github.com/expressjs/generator/issues/141

Honestly, the deprecation warning is pretty gnarly and since Pug _is_ Jade, I think it's logical to just rip off the bandaid and do it rather than rabbit-holing on alternatives.

**Comment by dougwilson** [comment]
Hi @fluxsauce I would say this is a duplicate issue for the one you linked to. Certainly replacing jade with pug is up for consideration, but pug still hasn't actually released a stable version yet, and has been constantly in flux, from being in alpha forever, then beta forever and now sitting in RC.

**Comment by dougwilson** [comment]
Additional information from that issue in why we have not changed it yet is because there are many tutorials out there that say `install express-generator` and then run it without params and exact to get Jade files and explain things with the `.jade` template files. I have been emailing those tutorials to either add `@...` to the install to get a specific generator install, to add `--view=jade` if they want to keep using Jade or add `--view=pug` and update their tutorial to reflect Pug. I have gotten quite a few to change so far, as according to the plain in the referenced thread.

**Comment by dougwilson** [comment]
If you can help get tutorials updated, that would be a big help as well 👍

**Comment by fluxsauce** [comment]
> If you can help get tutorials updated, that would be a big help as well
@dougwilson can you be more specific, IE which tutorials are you speaking of?

**Comment by dougwilson** [comment]
There are a lot out there, and I've gotten a lot of them changed and am basically just trying to get the ones that are at the top of the Google search results. For example:

- https://www.tutorialspoint.com/nodejs_online_training/nodejs_express_generator.asp
- http://www.fullstackjs.com/book/4/web-app-express-gen.html
- http://cwbuecheler.com/web/tutorials/2013/node-express-mongo/

Getting the tutorials that at least turn up at the top of search results has come up multiple times by folks not even involved in Express https://github.com/expressjs/generator/issues/141#issuecomment-256500680 and https://github.com/expressjs/generator/issues/141#issuecomment-263658599

**Comment by kid1412621** [comment]
how about now? https://www.npmjs.com/package/pug
