### ISSUE TITLE
add support for cors

### ISSUE THREAD

**Issue by rnovec** [expressjs/generator#262]
Hi,

This is a powerful tool to generate kickstart ExpressJS projects, but I always need to add cors package myself when I kickstart a project and consume my API in clients such as Vue, Angular or React.

Why not add this library and middleware as the same way that body and cookies parsers?

Is there any particular reason for that? If not, I can make change and and create a pull request.

**Comment by dougwilson** [comment]
The main reason is there is no good default value for CORS -- in fact, the best "default" one could argue would be to default to "secure", which is to not include CORS, as CORS opens up your resources to allow other sites to access things they would not otherwise be allowed to access.

That is to say, the CORS system was created by the web browsers and standards bodies to be an opt-in mechanism, and since it is security-related, it would definately be pounced upon by the "secure by default" groups if it was there by default.

The best thing for people to do is to add it when they know they need it and what settings they need to actually do with it, if that make sense.
