### ISSUE TITLE
Where is the logic?

### ISSUE THREAD

**Issue by GuidoS** [expressjs/generator#83]
I cannot seem to find the logic around the choices made within the basic setup when creating the scaffolding using the express-generator. As a NewB I find it very confusing to try and keep up with the structure of the scaffolding laid out. 

For example, I based on the [routing documentation](http://expressjs.com/guide/routing.html) I cannot seem to understand why you would generate a seperate module or where to handle the keys in this setup. Also, what is the order, is it all '/' checked in router then '/' user?

Also... the complicated npm script to for start, I would love to see a document explaining that choice.

I believe in best practices and really appreciate how easy it is to setup the scaffolding, I just wish I knew why this setup was chosen and how it fits into the express documentation.

**Comment by tsurantino** [comment]
Hey Guido,

I am not the project author but I thought that I'd help answer your questions based on my experience with `express-generator` so far. Broadly, you should be careful directing some of the "how it works" questions to this project because `express-generator` is not responsible for explaining how it works. 

With respect to routes being located in a separate file - you can actually find this documented on the Express website [here](http://expressjs.com/guide/routing.html#express-router). The order of the routes is in the order that they are listed in `app.js`, so that would mean that when `express-generator` creates a project, the project routes come before any `app` defined routes. 

I found `express-generator` incredibly useful when starting out and so I hope with the information above you have as good of an experience as I did. Best of luck!

**Comment by GuidoS** [comment]
@tsurantino thanks for your thoughts.

I would disagree with you about asking "how it works". If the generator is the basis on which the scaffolding is setup and the documentation around the express framework dos not discuss the current design choices in the generator, then I think the authors of the generator should be able to let us know what design choices they have made and what the proper way to work with it is.

I guess my biggest issue is that there is no documentation of using the current scaffolding setup that is being generated anywhere, so you have to know a lot about express and how it works prior to using the scaffolding. Which makes the scaffolding a little less useful if you do not know why choices were made or how to use them.

**Comment by dougwilson** [comment]
So our main documentation site is expressjs.com , which only the base API docs in READMEs here, so long explanations would belong on expressjs.com anyhow. We have come a long way in getting richer documentation on the site and would love for you to open an issue regarding this over at https://github.com/strongloop/expressjs.com so our team can get this addressed on our site :)

**Comment by GuidoS** [comment]
Thanks for the feedback @dougwilson
