### ISSUE TITLE
Add support for dust template engine

### ISSUE THREAD

**Issue by nbro** [expressjs/generator#90]
Dust is quite used template engine nowadays, and it would be nice to be able to have a generated with with our preferred engine. Is it possible to add it?

This generator is nice, but it lacks of many options. A generator would be really useful if customisable, IMO.

**Comment by dougwilson** [comment]
Hi! Both are great suggestions! We'll put the adding of `dust` on our backlog to get added; if you have time and want to contribute a pull request adding it, that would be amazing, especially since we have not used that templating, so will also need to understand it enough to make some templates in it as well.

As for customization, that sounds good too! Can you provide some specifics on exactly what "customisable" means to you and what this module would look like if it were this way?

**Comment by dossan** [comment]
I could for sure provide simple Dust templates as the ones provided for example for jade. By customisable I mean for example the possibility to specify the modules, maybe by having a config file so that we don't have to specify them every time, or something like that.You could also introduce an interface that guides the user in the creation of the app. These are just some ideas, but of course some might not be so useful at the end..

**Comment by dougwilson** [comment]
Re: sample Dust templates, that would be very helpful!

Re customization, is that similar to the proposal in #80 ?

**Comment by dossan** [comment]
For providing the templates, should I fork the repo and then add them to the `templates` folder?

Yes, something like that...

**Comment by dougwilson** [comment]
> For providing the templates, should I fork the repo and then add them to the templates folder?

Sure, that works :) You can add the link to the commit here. You can even make it as a PR, even if incomplete and I can pick it from there. Whatever you think works best :)

> Yes, something like that...

Cool! If you have any additional thoughts to add to that issue, please feel free :)

**Comment by loganhuskins** [comment]
Still looking for Dust templates? I'd be more than happy to do that for the project.

**Comment by dougwilson** [comment]
@loganhuskins absolutely! You can find the most recent conversation on this at https://github.com/expressjs/generator/pull/121#issuecomment-255420551

**Comment by dougwilson** [comment]
It's finally landing in the 4.15 version of the generator !
