### ISSUE TITLE
there's a bug in app.js

### ISSUE THREAD

**Issue by lifeiscontent** [expressjs/generator#97]
when I define a variable called `users` and set it to an object in app.js the whole app blows up.

what gives?

**Comment by dougwilson** [comment]
Hi! I've never heard of such a thing. Can you provide a copy of the `app.js` that blows up and what "blows up" means? I assume it means there is an error, and if so, please paste what that is as well.

**Comment by gokaygurcan** [comment]
Hello.
I think, what s/he was trying to say is defining a variable named `users` will conflict with the one you use for routers.

app.js : line 9:
`var users = require('./routes/users');`

app.js : line 26
`app.use('/users', users);`

If you define another thing with the same name, it'll 'blow up' at line 26. And that's totally normal because of the nature.

**Comment by dougwilson** [comment]
Thanks, @gokaygurcan ! I'm going to close this, but @lifeiscontent , I can re-open if you can provide further explanation on the nature of your issue :)
